twig:
    debug: "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    exception_controller: null
    form_themes: ["bootstrap_4_layout.html.twig"]
    paths:
          "%kernel.project_dir%/templates": images
          "%kernel.project_dir%/public/assets/images": templates
